### PR TITLE
Adds a way to enable/disable commands.

### PR DESCRIPTION
**Pull request by xaoseric**
This adds a way to enable/disable commands.

### CODE REVIEW

**Comment by BennyDoesStuff** [comment]
Nice summary of everything that should be done.

Fun commands ~ If you check #2 you can see a list of possible commands to include

Music Bot ~ For the first launch of this, we should focus on just having the music bot play music from Youtube. In the future, we could take advantage of the Spotify API to get a list of songs from a playlist and then look up those songs on Youtube so people can queue and play Spotify playlists without having ads if they don't have premium.

**Comment by Sniped** [comment]
For the Spotify API, how are we going to maintain the premium status of the account we use?

**Comment by Sniped** [comment]
(include this as well)

**Comment by BennyDoesStuff** [comment]
> For the Spotify API, how are we going to maintain the premium status of the account we use?

If I'm correct, I know the current Minehut music bot (Red Discord Bot) does it by using the API to look up all the names of the songs in the playlist, then it searches those song names on Youtube and queues it from Youtube onto the playlist. It doesn't require premium status at all since anyone can create an API key, that's how I set it up for the current MH bot and it seems to work fine. See below

~ Code (You might not know Python but it's fairly easy to understand what it's doing)
Code

(https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/audio/audio.py)

**Comment by Sniped** [comment]
Status update on the panel, got down a bit of the design.

**Comment by BennyDoesStuff** [comment]
I like it! Some feedback on that so far:

- Maybe make the Minehut logo a bit darker (not as transparent)
- What about adding a smaller Minehut logo in the top left next to the "Control Panel" wording similar to the one on the main Minehut panel?
Pic

Also kinda curious, what are you going to be using for the site? Nextjs?

**Comment by Sniped** [comment]
The site’s using Express for backend and EJS for frontend. I’ll make the logo a little less transparent and add it onto the navbar as well. Also, what should the dashboard include on the front? Gotta give it some content otherwise it looks dull.

**Comment by BennyDoesStuff** [comment]
I guess what we can include is some basic stats about the Discord server such as:

- People in the Discord server
- People online in the Discord server
- Number of people in voice channels
- Anything similar to that I guess

**Comment by Sniped** [comment]
What I got done today, I quite like it so far.

**Comment by Sniped** [comment]
The reason the last three are `N/A` because no data has been collected yet and I don't need to start collecting data until we're ready for release on prod.

**Comment by BennyDoesStuff** [comment]
I like it, we could probably update the look a bit but otherwise, I think it's a nice start.

**Comment by Sniped** [comment]
finished documentation, this also finishes command storing in a database for full customization client-side (website)

**Comment by Sniped** [comment]
I've decided to scrap my current progress and go for a better design, this time it will be material bootstrap. I will also be writing the new website in React rather than using express EJS. I will include multi guild support as suggested in #16. The main intention I'm going for is customization, we could also include live statistics that will update when they change.

**Pull request closed without merging**
