### PR TITLE
fix for getMCOwnerName

### PR DESCRIPTION
**Pull request by xaoseric**
This fixes the getMCOwnerName(String UUID) method in com.minehut.discordbot.util.Bot

### CODE REVIEW

**Comment by MatrixTunnel** [comment]
Oops, guess I forgot to push that

**Comment by BennyDoesStuff** [comment]
If you are boosting the Minehut Discord, your vote skip should count for 2 people instead of 1.

**Comment by BennyDoesStuff** [comment]
The queue for songs should have a limit of 25 songs. Staff should be able to bypass this. Would prevent things like this from happening in the music channel.

WhatAMess

**Comment by Sniped** [comment]
> The queue for songs should have a limit of 25 songs. Staff should be able to bypass this. Would prevent things like this from happening in the music channel.
> 
> WhatAMess

> If you are boosting the Minehut Discord, your vote skip should count for 2 people instead of 1.

Both noted 👌

**Comment by theminecoder** [comment]
Gonna close this in favour of using an already known bot for this so we don't have to deal with YouTube downloading

**Pull request merged**
