### PR TITLE
Update Bot

### PR DESCRIPTION
**Pull request by MatrixTunnel**
This update contains several updates and fixes to the code. This has been tested and should work fine. If anything is broken let me know :)

### CODE REVIEW

**Comment by Sniped** [comment]
Command documentation is going to be added which the public will be able to use without authentication, search bar isn't going to be added in the initial release though.

**Comment by Sniped** [comment]
#3 will also be added, should we link the command to said documentation @BennyDoesTheStuff ?

**Comment by BennyDoesStuff** [comment]
hmm, I think we could. We could probably list some of the major and useful commands people might use and at the end of the message/embed, just include a message saying:

"Learn more about all the features and commands you can use in the bot here!"

or something like that

**Comment by Sniped** [comment]
update on prev. comment

yes it will require authentication to determine what to show the user

**Pull request merged**
